### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by acheong08** [sivukhin/godjot#2]
Hello there!

Thank you so much for creating this repo. I'm interested in writing a `djot` parser for zig and would like to use this repository as reference. Could you possibly add a license (any) to make it legal for forking/referencing?

**Comment by sivukhin** [comment]
Yes, sure. Feel free to use the source code as a reference - added MIT license to the repo.

Note that `godjot` is in it's very early stage. I use it for my own blog and still fixing some bugs occasionally - so you must use it as a reference at your own risk :-)

Also note, that I implemented `godjot` based only on the official documentation and in case of ambiguity I made decisions without consulting with reference JS implementation.
