### ISSUE TITLE
pkg.go.dev license issues

### ISSUE THREAD

**Issue by rokf** [sivukhin/godjot#5]
Hello,

I wanted to check the docs for this package on https://pkg.go.dev/github.com/sivukhin/godjot@v1.0.1 and noticed that it's having problems with the license. It doesn't display anything because there's no license in the 1.0.1 release if I'm not mistaken.

Looks like you'll have to push another tag (version) to make that work, so that it picks up the MIT license which you've added in February?

Thanks!

**Comment by sivukhin** [comment]
Hi, thanks for the interested in `godjot`!

I published v1.0.2 tag which is basically fresh master with LICENSE which docs already available here: https://pkg.go.dev/github.com/sivukhin/godjot@v1.0.2
Also, spotted one bug after published v1.0.3 which should be available at pkg.go.dev soon

I use `godjot` for personal projects - so there can be bugs or subtleties in API. Feel free to file an issue or PRs with fixes and improvements.
Also, if you plan to use `godjot` in open-source project - you can mention it here and I will look after it if there will be some major changes in API of the library.

**Comment by rokf** [comment]
Thank you 🙂
